export const countries = [
    { code: 'RU', name: 'Россия', dialCode: '+7', flag: '🇷🇺' },
    { code: 'KZ', name: 'Казахстан', dialCode: '+7', flag: '🇰🇿' },
    { code: 'BY', name: 'Беларусь', dialCode: '+375', flag: '🇧🇾' },
    { code: 'UA', name: 'Украина', dialCode: '+380', flag: '🇺🇦' },
    { code: 'US', name: 'США', dialCode: '+1', flag: '🇺🇸' },
    { code: 'GB', name: 'Великобритания', dialCode: '+44', flag: '🇬🇧' },
    { code: 'DE', name: 'Германия', dialCode: '+49', flag: '🇩🇪' },
    { code: 'FR', name: 'Франция', dialCode: '+33', flag: '🇫🇷' },
    { code: 'IT', name: 'Италия', dialCode: '+39', flag: '🇮🇹' },
    { code: 'ES', name: 'Испания', dialCode: '+34', flag: '🇪🇸' },
    { code: 'PT', name: 'Португалия', dialCode: '+351', flag: '🇵🇹' },
    { code: 'NL', name: 'Нидерланды', dialCode: '+31', flag: '🇳🇱' },
    { code: 'BE', name: 'Бельгия', dialCode: '+32', flag: '🇧🇪' },
    { code: 'CH', name: 'Швейцария', dialCode: '+41', flag: '🇨🇭' },
    { code: 'AT', name: 'Австрия', dialCode: '+43', flag: '🇦🇹' },
    { code: 'PL', name: 'Польша', dialCode: '+48', flag: '🇵🇱' },
    { code: 'CZ', name: 'Чехия', dialCode: '+420', flag: '🇨🇿' },
    { code: 'SE', name: 'Швеция', dialCode: '+46', flag: '🇸🇪' },
    { code: 'NO', name: 'Норвегия', dialCode: '+47', flag: '🇳🇴' },
    { code: 'FI', name: 'Финляндия', dialCode: '+358', flag: '🇫🇮' },
    { code: 'DK', name: 'Дания', dialCode: '+45', flag: '🇩🇰' },
    { code: 'TR', name: 'Турция', dialCode: '+90', flag: '🇹🇷' },
    { code: 'GR', name: 'Греция', dialCode: '+30', flag: '🇬🇷' },
    { code: 'IL', name: 'Израиль', dialCode: '+972', flag: '🇮🇱' },
    { code: 'AE', name: 'ОАЭ', dialCode: '+971', flag: '🇦🇪' },
    { code: 'SA', name: 'Саудовская Аравия', dialCode: '+966', flag: '🇸🇦' },
    { code: 'CN', name: 'Китай', dialCode: '+86', flag: '🇨🇳' },
    { code: 'JP', name: 'Япония', dialCode: '+81', flag: '🇯🇵' },
    { code: 'KR', name: 'Корея Южная', dialCode: '+82', flag: '🇰🇷' },
    { code: 'IN', name: 'Индия', dialCode: '+91', flag: '🇮🇳' },
    { code: 'ID', name: 'Индонезия', dialCode: '+62', flag: '🇮🇩' },
    { code: 'TH', name: 'Таиланд', dialCode: '+66', flag: '🇹🇭' },
    { code: 'VN', name: 'Вьетнам', dialCode: '+84', flag: '🇻🇳' },
    { code: 'MY', name: 'Малайзия', dialCode: '+60', flag: '🇲🇾' },
    { code: 'SG', name: 'Сингапур', dialCode: '+65', flag: '🇸🇬' },
    { code: 'PH', name: 'Филиппины', dialCode: '+63', flag: '🇵🇭' },
    { code: 'BR', name: 'Бразилия', dialCode: '+55', flag: '🇧🇷' },
    { code: 'AR', name: 'Аргентина', dialCode: '+54', flag: '🇦🇷' },
    { code: 'MX', name: 'Мексика', dialCode: '+52', flag: '🇲🇽' },
    { code: 'CA', name: 'Канада', dialCode: '+1', flag: '🇨🇦' },
    { code: 'AU', name: 'Австралия', dialCode: '+61', flag: '🇦🇺' },
    { code: 'NZ', name: 'Новая Зеландия', dialCode: '+64', flag: '🇳🇿' },
    { code: 'ZA', name: 'ЮАР', dialCode: '+27', flag: '🇿🇦' },
    { code: 'EG', name: 'Египет', dialCode: '+20', flag: '🇪🇬' },
    { code: 'NG', name: 'Нигерия', dialCode: '+234', flag: '🇳🇬' },
    { code: 'KE', name: 'Кения', dialCode: '+254', flag: '🇰🇪' }
];